document.writeln("<div id=\'side-bar\'>");
document.writeln("    <div class=\'overlay\'></div>");
document.writeln("    <!-- Sidebar -->");
document.writeln("    <nav class=\'navbar navbar-inverse navbar-fixed-top\' id=\'sidebar-wrapper\' role=\'navigation\'>");
document.writeln("        <ul class=\'nav sidebar-nav\'>");
document.writeln("            <li class=\'sidebar-brand\'>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    宿舍管理系统");
document.writeln("                </a>");
document.writeln("            </li>");
document.writeln("            <div class=\'bar-header-s\'>日常操作管理</div>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'><i class=\' fa fa-bell\'></i>&nbsp;学生违纪登记</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'><i class=\' fa fa-exchange\'></i>&nbsp;物品借用登记</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'><i class=\' fa fa-wrench\'></i>&nbsp;维修信息登记</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("                <a href=\'#\'><i class=\' fa fa-comment\'></i>&nbsp;访客信息登记</a>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("        <ul class=\'nav sidebar-nav second\'>");
document.writeln("            <div class=\'bar-header-s\'>学生住宿管理</div>");
document.writeln("            <li><a href=\'#\'><i class=\'fa fa-users\'></i>&nbsp;预分配宿舍</a></li>");
document.writeln("            <li><a href=\'#\'><i class=\'fa fa-edit\'></i>&nbsp;学生入住登记</a></li>");
document.writeln("            <li><a href=\'#\'><i class=\'fa fa-minus-square\'></i>&nbsp;学生退宿</a></li>");
document.writeln("            <li><a href=\'#\'><i class=\'fa fa-retweet\'></i>&nbsp;宿舍调整</a></li>");
document.writeln("            <li><a href=\'#\'><i class=\'fa fa-share\'></i>&nbsp;学生外宿</a></li>");
document.writeln("        </ul>");
document.writeln("    </nav>");
document.writeln("    <!-- /#sidebar-wrapper -->");
document.writeln("");
document.writeln("    <div id=\'wrapper\'>");
document.writeln("        <button type=\'button\' class=\'hamburger is-closed animated fadeInLeft\' data-toggle=\'offcanvas\'>");
document.writeln("            <span class=\'hamb-top\'></span>");
document.writeln("            <span class=\'hamb-middle\'></span>");
document.writeln("            <span class=\'hamb-bottom\'></span>");
document.writeln("        </button>");
document.writeln("    </div>");
document.writeln("</div>");